In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [7]:
filename="iris.csv"
dataset =pd.read_csv(filename)
x= dataset[['SepalLengthCm','SepalWidthCm','PetalLengthCm','PetalWidthCm']]
y= dataset['Species']

from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.3)

from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
xtrain= sc.fit_transform(xtrain)
xtest= sc.transform(xtest)

from sklearn.naive_bayes import GaussianNB
gmodel=GaussianNB()
gmodel.fit(xtrain,ytrain)

GaussianNB(priors=None)

In [9]:
gpred = gmodel.predict(xtest)
from sklearn.metrics import confusion_matrix

gcm = confusion_matrix(ytest,gpred)
print(gcm)

[[14  0  0]
 [ 0 14  2]
 [ 0  0 15]]


In [11]:
from sklearn.metrics import accuracy_score
accuracy_score(ytest,gpred)

0.9555555555555556

In [13]:
print("probability of falling into each class")
print(gmodel.predict_proba([[5,3,1.2,2]]))
print("input classified into")
ans=gmodel.predict([[5,3,1.2,2]])
print(ans)

probability of falling into each class
[[  2.55013826e-265   6.72216133e-020   1.00000000e+000]]
input classified into
['Iris-virginica']
